name: Update Dropzones

on:
  schedule:
    - cron: "0 9 * * 1"
  workflow_dispatch:

permissions:
  contents: write   # ✅ allow pushing commits

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # ✅ built-in token with write perms

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests
          python -m playwright install --with-deps chromium

      - name: Run scraper
        run: python tools/scraper.py

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add data/dropzones.json   # ✅ ensure path matches
          git commit -m "Auto-update dropzones.json [skip ci]" || echo "No changes to commit"
          git push
